### PR TITLE
Add mailman config

### PR DESCRIPTION
**Pull request by SuperQ**
Switch to debops mailman/postfix roles.

### CODE REVIEW

**Comment by SuperQ** [comment]
I've decided that DebOps is too much of a dependency nightmare to use.

**Comment by drybjed** [comment]
@SuperQ I'm sorry to hear that. DebOps roles are designed to focus on specific applications/services and to pass dependent configuration to other roles via dependent variables. You can thus select what roles to use for different services if you wish. However these dependencies are not readily apparent if you don't know what to look for.

Would you care to elaborate a bit more what problems did you encounter that forced you to drop DebOps? There might already be a solution to these issues in the project.

**Comment by SuperQ** [comment]
@drybjed The difficulty is that there are too many interdependent roles.  For example, the `debops.secret` role seems like a terrible replacement for ansible vault secret handling.  Another example is that he `debops.postfix` role depends on `debops.ferm`, which is some kind of firewall role I do not want.

If I were managing everything with the DebOps project, it would be useful, but due to the excessive role dependency graph, I end up dragging in tons of crap I don't want to have.

**Comment by drybjed** [comment]
@SuperQ Thanks for your answer. Of course it's your choice if you use DebOps roles or not, however let me explain why the things you mentioned are there.

Ansible role dependencies can be defined as "hard" and "soft" - at least that's what I'm calling them in DebOps. Hard dependencies are defined in the role's `meta/main.yml` file and they are basically mandatory - without them the role wouldn't work as expected at all. Soft dependencies are defined as other roles in the playbook, usually executed before the role in question, with custom variables defined by other roles. These roles can be dropped when you write your own playbook, as long as you handle the equivalent functionality yourself.

The [`debops.secret`](https://github.com/debops/ansible-secret/) role is a hard dependency. This role maintains a directory beside the inventory directory on Ansible Controller host which stores passwords, certificates, private keys, and other data. I agree that it's a poor replacement for `ansible-vault`, however I chose this method to handle secrets because `ansible-vault` does not support randomly generated passwords via `lookup("password")`, or management of other data dynamically, like private keys/certificates. DebOps generates random passwords and handles its own PKI automatically because of `debops.secret`.

Of course it has some caveats. I assume that the Ansible Controller host is a trusted, and secure host (otherwise, why are you using it?). You use an encrypted filesystem to store Ansible configuration, so the data is protected at rest. For additional security, you can use `encfs` to further protect the `secret/` directory at rest and easily access it during Ansible operation. Other people use stuff like `git-crypt` to secure the sensitive files in the `git` repository.

I wish that Ansible had some easy way to switch between lookup plugins, with this the `password` lookup could be switched with say, `consul_kv` when it's available. But it's a feature that needs to be implemented in Ansible directly, so it's out of my hands for now.

The [`debops.ferm`](https://github.com/debops/ansible-ferm/) role is a soft dependency, defined in the [`debops.postfix` playbook](https://github.com/debops/debops/blob/master/ansible/playbooks/service/postfix.yml#L25-L28). It configures the `iptables` and `ip6tables` firewall and uses the [`postfix__ferm__dependent_rules`](https://github.com/debops/ansible-postfix/blob/master/defaults/main.yml#L1321-L1354) variable defined in the `debops.postfix` role to configure the firewall for SMTP access. It can be safely dropped from the playbook, along with the [`debops.etc_aliases`](https://github.com/debops/ansible-etc_aliases/) role if you wish. The `debops.postfix` role doesn't touch the firewall by itself, so as long as there are no rules, or you maintain the firewall yourself, it should work just fine.

So, in overall, the excessive dependency graph of `debops.postfix` comes to:

- `debops.ansible_plugins` which provides some filter plugins used by DebOps roles
- `debops.secret` which maintains a directory on Ansible Controller

The rest is totally optional.

**Pull request closed without merging**
